config/routes.rb
JqueryTest::Application.routes.draw do
	
  resources :questions

  resources :surveys do
  	get 'add_question', :on => :member
  end

  resources :users do
  	get 'show_more', :on => :member
  end
  resources :articles

  resources :posts do
  	collection do
  		get 'test'
  	end
  	resources :comments
  end
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def index
		@comments = Comment.all
		respond_to do |format|
			format.html # index.html.erb
			format.rss
		end
	end
	
	 def create
	 	@post = Post.find(params[:post_id])
	 	print "In create action comments controller"
	 	@comment = @post.comments.create(params[:comment])
	 	# redirect_to :back, :notice => "Thanks for commenting!"
	 	respond_to do |format|
	 		format.js
	 	end
    # @comment = Comment.create!(params[:comment])
    # flash[:notice] = "Thanks for commenting!"
    # respond_to do |format|
      # format.html { redirect_to comments_path }
      # format.js
    # end
  end

  def destroy
     @comment = Comment.find(params[:id])
     @comment.destroy
     respond_to do |format|
       # format.html { redirect_to comments_path }
       format.js
     end
   end
	
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<%= div_for comment do %>
  <span class="dateandoptions">
    Posted <%=time_ago_in_words(comment.created_at)%> ago<br />
    <%= link_to 'Delete', comment_path(comment), :method => :delete, :class => "delete", :remote => true  %>
  </span>
	<p><b><%= comment.name %></b> wrote:</p>
	<br />
  <%= content_tag(:p, comment.content, :class => "comment-body") %>
<% end %>

app/views/comments/_comment_view.html.erb
<%= content_tag_for(:div, comment) do %>
	<div class="title_comment">
		<%= content_tag(:span, comment.name) %> says:
		<div class="time_comment">
			Posted <%=time_ago_in_words(comment.created_at)%> ago<br />
		</div>
		<div class="delete_comment">
			<%= link_to "Delete", post_comment_path(Post.find(comment.post_id), comment), :method => :delete, :remote => true%>
		</div>
	</div>
	<div class="body_comment">
		<%= comment.content %>
	</div>
<% end %>

app/views/comments/index.html.erb
<span id="comments_count"><%= pluralize(@comments.count, "Comment") %></span>
<div id="comments">
  <%= render :partial => @comments, :locals => { :list => true } %>
</div>

<hr />

<div id="comment-notice"></div>

<h2>Say something!</h2>
<%= form_for Comment.new, :remote => true do |f| %>
	<%= f.label :name, "Your name" %><br />
	<%= f.text_field :name %><br />
	<%= f.label :content, "Comment" %><br />
	<%= f.text_area :content, :rows => 8 %><br />
	<%= f.submit "Add comment" %>
<% end %>