config/routes.rb
JqueryTest::Application.routes.draw do
	
  resources :questions

  resources :surveys do
  	get 'add_question', :on => :member
  end

  resources :users do
  	get 'show_more', :on => :member
  end
  resources :articles

  resources :posts do
  	collection do
  		get 'test'
  	end
  	resources :comments
  end
  

end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments, :dependent => :destroy
	has_many :tests
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def test
		@post = Post.first
		respond_to do |format|
			format.js
		end
	end
	
  def index
  	@posts = Post.all
  	
    @post = Post.new

    respond_to do |format|
      format.html
    end
  end
  
  def show
  	@post = Post.find(params[:id])
  	
  end
  
  def edit
  	@post = Post.find(params[:id])
  end

  def create
  	@post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to(posts_url,
                    :notice => 'Post was successfully created.') }
        format.js
      else
        format.html { redirect_to(posts_url) }
      end
    end
  end
  
  def update
  	@post = Post.find(params[:id])
  	print "\nparams\n"
  	print params[:post][:title]
  	
  	respond_to do |format|
  		if @post.update_attributes(params[:post])
  			format.html { redirect_to(@post, :notice => "Post was updated.") }
  		else
  			format.html { render :action => 'edit' }
  		end
  	end
  end

  def destroy
  	@post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to(posts_url) }
      format.js
    end
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post, :remote => true) do |f| %>
  <div class="field">
  	<%= f.label :title %><br/>
  	<%= f.text_field :title %><br/>
  	<%= f.label :body %><br/>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<%= content_tag_for(:li, post) do %>
  <%= post.body %>
  (<%= link_to 'Delete', post, :confirm => 'Are you sure?',
  :method => :delete, :remote => true %>) 
  (<%= link_to 'View', post_path(post) %>)
<% end %>

app/views/posts/_post_form.html.erb
<%= form_for post do |f| %>
	<div class="field">
  	<%= f.label :title %><br/>
  	<%= f.text_field :title %><br/>
  	<%= f.label :body %><br/>
    <%= f.text_area :body %><br/>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_post_view.html.erb
<%= link_to "Edit post", edit_post_path(post) %>
<%= content_tag_for (:div, post) do %>
	<div class="title"><%= post.title %></div>
	<div class="body"><%= post.body %></div>
	<div class="comments" id="post_comments_<%= post.id %>">
		<%= content_tag(:h2, "Comments:") %>
		<%= render(:partial => '/comments/comment_view', :collection => post.comments, :as => :comment) || "No comment"%>
	</div>
	<div class="add_comment">
		<%= content_tag(:h2, "Add comment")%>
		<%= form_for([post, post.comments.build], :html => {:id => "form_comment_#{post.id}"}, :remote => true) do |f| %>
			<div class="field">
				<%= f.label :name %><br/>
				<%= f.text_field :name %><br/>
				<%= f.label :content %><br/>
				<%= f.text_field :content %>
			</div>
			<div class="actions">
				<%= f.submit "Submit"%>
			</div>
			
		<% end %>
	</div>
<% end %>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<h1>Edit post</h1>
<%= render :partial => 'post_form', :object => @post, :as => :post%>

app/views/posts/index.html.erb
<h1>Posts#index</h1>
<p>Find me in app/views/posts/index.html.erb</p>
<hr/>
<h1>Test jQuery normal</h1>
<div id='test'>
	Hello world, test jquery
</div>
<br/>
<button class="show-hide">Show/Hide div</button>
<%= link_to "Show/Hide div", "#", :class => 'show-hide' %>
<br/>

<ul id="abc">
	
</ul>
<%= link_to "Add post", test_posts_path, :remote => true %>

<hr/>
<h1>Posts</h1>

<div id="post_form">
  <%= render 'form' %>
</div>

<ul id="posts">
  <%= render @posts %>
</ul>
<hr/>
<h1>Test render</h1>
<div id="all_post">
	<%= render :partial => 'post_view', :collection => @posts, :as => :post %>
</div>

app/views/posts/show.html.erb
<h2>Show post</h2>
<div class="post_container">
	<div class="title">
		<%= @post.title %>
	</div>
	<div class="body">
		<%= @post.body %>
	</div>
</div>
<%= link_to 'Back', posts_path %>